# -*- coding: utf-8 -*-
"""circum_sphere

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YncydsXf5p5nAbBU8vn3qlouo82Y8f18
"""

import numpy as np
from scipy.spatial import Delaunay
import os


def get_circumradius(x, y, z):
    a = np.linalg.norm(y - z)
    b = np.linalg.norm(x - z)
    c = np.linalg.norm(x - y)

    area = np.linalg.norm(np.cross(y - x, z - x)) / 2

    return (a * b * c) / (4 * area)


def save_stl(path, name, triangles):
    with open(path, "w") as file:
        file.write(f"solid {name}\n")

        for triangle in triangles:
            x, y, z = triangle

            file.write("facet normal 0 0 0\n")
            file.write("\touter loop\n")
            file.write(f"\t\tvertex {x[0]} {x[1]} {x[2]}\n")
            file.write(f"\t\tvertex {y[0]} {y[1]} {y[2]}\n")
            file.write(f"\t\tvertex {z[0]} {z[1]} {z[2]}\n")
            file.write("\tendloop\n")
            file.write("endfacet\n")

        file.write(f"endsolid {name}\n")


# (3D)
# Open the file and read the vertices as strings
with open("bunny.xyz", "r") as f:
    vertex_strings = f.readlines()

# Convert the vertex strings to a NumPy array of shape (N, 3)
points3D = np.zeros((len(vertex_strings), 3))
for i, vertex_str in enumerate(vertex_strings):
    vertex_arr = [float(coord) for coord in vertex_str.strip().split()]
    points3D[i] = vertex_arr


tri = Delaunay(points3D)
alphas = [0.0008]

for alpha in alphas:
    name = f"bunny_{alpha}"
    path = os.path.join("stl", f"{name}.stl")
    triangles = []

    for tetra in tri.simplices:
        for k in range(len(tetra)):
            x, y, z = points3D[tetra[k % 4]], points3D[tetra[(k + 1) % 4]], points3D[tetra[(k + 2) % 4]]
            r = get_circumradius(x, y, z)

            if r <= alpha:
                triangles.append((x, y, z))

    save_stl(path, name, triangles)
    print(name)
